global:
  name: vst-f
  phase: train
  stage: train-super
  workdir: workdir
  seed: ~
dataset:
  train: {
    roots: ['../ABINet/data/training/MJ/MJ_train/', 
            '../ABINet/data/training/MJ/MJ_test/', 
            '../ABINet/data/training/MJ/MJ_valid/', 
            '../ABINet/data/training/ST'],
    batch_size: 2
  }
  test: {
    roots: ['../ABINet/data/evaluation/IIIT5k_3000', 
            '../ABINet/data/evaluation/SVT', 
            '../ABINet/data/evaluation/SVTP',
            '../ABINet/data/evaluation/IC13_857',
            '../ABINet/data/evaluation/IC15_1811',
            '../ABINet/data/evaluation/CUTE80'],
    batch_size: 2
  }
  data_aug: True
  multiscales: False
  num_workers: 0

training:
  epochs: 10
  show_iters: 50
  eval_iters: 3000
  save_iters: 3000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [6, 4],
    gamma: 0.1,
  }

model:
  name: 'modules.model_vst.VSTModel'
  d_model: 512
  convnet: {
    blocks: [1,1,2,5,3],
    strides: [[1,1], [2,2], [1,1], [2,2], [2, 1]],
  }
  vision: {
    n_head: 8,
    dropout: 0.1,
    activate: relu,
    num_layers: 3,
    d_inner: 2048
  }
  interaction: {
    n_head: 8,
    dropout: 0.1,
    activate: relu,
    num_layers: 3,
    d_inner: 2048
  }
  
  semantic: {
    n_head: 8,
    dropout: 0.1,
    activate: relu,
    num_layers: 3,
    d_inner: 2048
  }
